### ISSUE TITLE
Determine URL

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#2] opened 2017-01-05 19:11 UTC
Once we figure out where the site will live (on the new MLN site, as a stand alone site, on Learning site...) we will need to determine the URL.

**Comment by hannahkane** [comment] 2017-01-05 19:41
Suggest we don't use Learning or another existing site. I'd vote for a stand-alone, but waiting to hear product/marketing considerations from others.

cc @xmatthewx @simonwex

**Comment by hannahkane** [comment] 2017-01-11 22:45
Confirmed we will use a stand-alone site. Will determine specific url via email, rather than here.

**Comment by mehan** [comment] 2017-01-13 22:12
Okay, it sounds like the top choice for URL is something in the vein of wirelesschallenge.mozilla.org.

**Comment by hannahkane** [comment] 2017-01-18 21:47
Great. @cadecairos - please see above. Feb 15 is our target date for launching this new web property which advertises two challenges we're producing in conjunction with the U.S. National Science Foundation.

Is there anything we need to do to ensure we're able to use this subdomain?

**Comment by cadecairos** [comment] 2017-01-18 22:09
@hannahkane How are we serving the site? dynamically on Heroku (django?) or is it a static website we can host on AWS S3?

In either case, I'll need to file a bugzilla bug to have a CNAME created for that subdomain on mozilla.org, but I can't do that until I understand how we're deploying it first.

**Comment by simonwex** [comment] 2017-01-19 00:48
@gvn can let you know what the requirements are. I believe initially it'll be a static site generator.

**Comment by gvn** [comment] 2017-01-19 18:49
@simonwex I'm not sure since I haven't been involved thus far with this project. I need to be briefed to establish reqs.

**Comment by hannahkane** [comment] 2017-01-19 21:34
@gvn - hoping you and @mmmavis have time to connect on this soon. For your reference, in-progress comps are here: https://redpen.io/yja7196949cc09f284. Let me know if you need additional context beyond that.

**Comment by gvn** [comment] 2017-01-19 21:46
If we use the same architecture as MLN then it can go on Heroku, S3, or any static web hosting service. Based on the comps I'd say the MLN architecture is a good choice. What I see is mostly static, with a few bits of dynamic UI (accordions).

I'm leaning toward Heroku for hosting because that gives us the option of adding some Node based server side code should we need it...

**Comment by mmmavis** [comment] 2017-01-31 19:21
+1 on having it on Heroku. @cadecairos I'll create a ticket on DevOps repo.

**Comment by mmmavis** [comment] 2017-01-31 19:25
DevOps ticket created: https://github.com/MozillaFoundation/mofo-devops/issues/450

**Comment by hannahkane** [comment] 2017-02-09 18:26
Closing this in lieu of the DevOps ticket.

**Closed as completed by hannahkane** 2017-02-09 18:26 UTC
